### PR TITLE
Fixing printing

### PR DESCRIPTION
**Pull request by jolyonb**
This pull request adds some statements to the theme CSS. These statements override some defaults in edX, in order to make printing possible within the platform. In the future, most of these statements could be incorporated into the edX CSS, rather than using !important incredible liberally. However, for the moment, they may printing work, which is better than the status quo.

### CODE REVIEW

**Comment by pdpinch** [comment]
@kboots-mit @JoeMartis Can you guys take a quick look at this, in particular the section that hides stuff: https://github.com/mitocw/edx-theme/pull/12/files#diff-af56540b674d5dbee26891f9d6306f52R253

Is there anything additional that you think should be in there?

**Comment by carsongee** [comment]
Thanks for the PR @jolyonb, can we get a before and after screen?  I think that may make it easier to review for those who don't want to have to setup a stack with the changes in it.

**Comment by carsongee** [comment]
For image mapped input, at least sometimes the image disappears:
image
and the screen:

image

This is from the https://github.com/edx/edx-demo-course

**Comment by carsongee** [comment]
Also, the run code button for code problems still shows:
image

**Comment by pdpinch** [comment]
Here's a before and after, comparing a page from the DevOps course on staging and on the mitxstack (with CSS changes):

checkboxes sample problems 0 001 on staging.mitx.mit.edu

checkboxes sample problems 0 001 on mitxstack with CSS changes

**Comment by pdpinch** [comment]
- I wish we had green check marks, but that seems to be an underlying issue in edX (i.e. they are missing from both). 
- the headers and footers seem to be an issue with how my browser is set up

So, no blockers.

**Comment by jolyonb** [comment]
Thanks for the testing, @carsongee. I've never used those problem types before; I'm just cloning the example repo now to test them.

The kitten/dog picture is difficult. The edX css is killing it, and I can't undo it by adding more code. The offending code is the following (which appears in a print media section):
`* { background: none repeat scroll 0 0 transparent !important;}`
which appears in lms-style-app-extend1.(bunch of hex).css. In particular, this kills the background image (which is how that image is embedded). I think that the !important needs to be removed, as this overrides everything.

As for the "run code" button, I couldn't get that to even show up in my stack (just cloning the repo led to a bunch of problems to begin with, and getting matlab stuff to show up just wasn't working).

**Comment by jolyonb** [comment]
@pdpinch If you ask your browser to stop printing headers/footers, it looks much prettier :-)

Ah, wasn't testing for green check marks (I guess for solution printing, that would be helpful). They work on multiple choice questions, but not on checkbox or option questions. Looking at how the checkboxes are implemented, it appears that the same code that it killing the kitten is killing the checkboxes (because they're made as background images).

**Comment by jolyonb** [comment]
I've fixed two more things:
- Sometimes, a blank page would be printed because of extra padding down the bottom. Now removed.
- Peter's issue with the header/footer being printed over was due to an issue with the edX default again. Now fixed (larger margin enforced).

**Pull request closed without merging**
