### PR TITLE
Removing code that's included in dogwood release

### PR DESCRIPTION
**Pull request by jolyonb**
Hey folks,

I'm not sure what stage of updatedness MITx is at, but if this PR is present in the system:
https://github.com/edx/edx-platform/pull/9122
then we should be removing all of the hacks that I previously introduced, as they are already incorporated into the system.

Best,
Jolyon

### CODE REVIEW

**Comment by jolyonb** [comment]
@pdpinch Poking this?

**Comment by pdpinch** [comment]
Not yet for this one (d06abb). 

Definitely after the dogwood upgrade. 

Is there a set of theme commits we should plan to revert? Is it just all of yours from this time period?

**Comment by jolyonb** [comment]
Ok, gotcha. Once d06abb is in the system, this is basically reverting a bunch of theme commits. This is just all of my fixes from the time period (mostly printing fixes).

**Comment by itsbenweeks** [comment]
@pdpinch - @kboots-mit and I have been looking into theming for dogwood, and would like to continue using this Stanford theme. Can we include Jolyon's change here and then make the proper adjustments?

**Comment by pdpinch** [comment]
This repo is no longer active. See https://github.com/mitodl/mitx-theme

**Pull request closed without merging**
